### ISSUE TITLE
Invoice Update The View Field

### ISSUE THREAD

**Issue by Sushantshr** [Sushantshr/Billing-App#2]
## Acceptance Criteria
- [x] Update the view to include all the information
- [x] Update the view to show the images according to the creation.

**Comment by stylesaniswi** [comment]
![image](https://github.com/user-attachments/assets/0f45b8a0-e70f-48f9-938d-c835bff9c0db)

**Comment by stylesaniswi** [comment]
![image](https://github.com/user-attachments/assets/169f95b7-db9e-4a56-adb1-82a32a405955)

**Comment by stylesaniswi** [comment]
- [x] Model for noteImages created

- [x] fix view crash after changing status
